import hashlib
import json
import logging
import uuid
from datetime import datetime, timezone
from typing import Dict, Any, List, Optional

from app.schemas.cost import (
    WorkloadInput,
    CostAnalysisResult,
    Recommendation,
    CostEstimateResponse,
    CostHealth
)
from app.services.cost_calculator import CostCalculator
from app.services.ai_service import ai_query_service
from app.config.settings import settings

logger = logging.getLogger(__name__)

GEMINI_COST_SYSTEM_PROMPT = """You are an expert Cloud Architecture & AWS Cost Optimization Principal Engineer specializing in Amazon DocumentDB and MongoDB-compatible workloads for small to medium enterprise applications.

You are analyzing an application workload and deterministic cost estimate generated by the InspectDB Cost Calculator.

### Your Objectives:
1. Identify the primary cost drivers (e.g., continuous idle compute hours, storage size, I/O amplification from high-write ratios, backup retention).
2. Identify potential waste and inefficient resource allocation.
3. Provide concrete, actionable, explainable, and prioritized architectural recommendations to optimize cost, performance, and reliability.
4. Clearly state trade-offs (e.g., Single-AZ vs Multi-AZ availability, scheduled startup latency vs 24/7 availability).
5. Identify any missing workload information or architectural assumptions that could impact actual billing.

### Critical Safety & Truthfulness Rules:
- DO NOT invent prices or claim access to live AWS billing APIs. You are analyzing architectural models and calculator estimates.
- DO NOT claim that you have inspected live AWS infrastructure.
- Always tie estimated savings directly to the deterministic calculator numbers provided in the prompt.
- For non-quantifiable optimizations (e.g. compound indexing to reduce I/O), explain the mechanism clearly without fabricating exact dollar amounts.
- All recommendations must be advisory.

### Required Structured JSON Response Format:
You MUST respond with a single valid JSON object following this exact schema:
{
  "summary": "Comprehensive 2-3 sentence executive summary of the cost analysis and architectural recommendations.",
  "cost_drivers": [
    "Description of primary cost driver 1",
    "Description of primary cost driver 2"
  ],
  "optimization_opportunities": [
    "Opportunity 1",
    "Opportunity 2"
  ],
  "deployment_observations": [
    "Deployment observation 1",
    "Deployment observation 2"
  ],
  "tradeoffs": [
    "Tradeoff 1",
    "Tradeoff 2"
  ],
  "risks": [
    "Risk 1",
    "Risk 2"
  ],
  "recommended_next_steps": [
    "Actionable step 1",
    "Actionable step 2"
  ],
  "recommendations": [
    {
      "id": "rec-1",
      "title": "Clear action-oriented title",
      "category": "compute | scheduling | storage | architecture | monitoring",
      "impact": "high | medium | low",
      "explanation": "Detailed rationale explaining why this recommendation is advantageous.",
      "reason": "Root cause workload factor that triggers this recommendation.",
      "estimated_impact": "High cost reduction (~78% compute savings) / Medium risk mitigation",
      "tradeoff": "Startup latency / reduced redundancy / operational complexity",
      "action": "Specific concrete change to configuration or operational posture.",
      "estimated_monthly_savings": 45.50,
      "trade_offs": [
        "Trade-off or risk 1",
        "Trade-off or risk 2"
      ],
      "implementation_steps": [
        "Step 1: ...",
        "Step 2: ...",
        "Step 3: ..."
      ]
    }
  ],
  "missing_information": [
    "Missing workload parameter or unconfirmed operational requirement 1"
  ]
}
"""

class CostOptimizerService:
    """
    Manages AWS DocumentDB cost estimation, Gemini-powered analysis,
    result caching, and historical recommendation tracking.
    """

    def __init__(self):
        self._cache: Dict[str, CostAnalysisResult] = {}
        self._history: List[CostAnalysisResult] = []

    def _generate_cache_key(self, workload: WorkloadInput) -> str:
        data = workload.model_dump_json()
        return hashlib.sha256(data.encode('utf-8')).hexdigest()

    async def analyze_workload(
        self,
        workload: WorkloadInput,
        force_refresh: bool = False
    ) -> CostAnalysisResult:
        cache_key = self._generate_cache_key(workload)

        if not force_refresh and cache_key in self._cache:
            cached = self._cache[cache_key]
            result = cached.model_copy(deep=True)
            result.is_cached = True
            return result

        # 1. Compute deterministic cost estimate and deployment comparison
        estimate_resp: CostEstimateResponse = CostCalculator.calculate_workload_costs(workload)

        # 2. Call Gemini for AI architectural analysis (or deterministic fallback if unconfigured)
        analysis_result = await self._generate_gemini_analysis(workload, estimate_resp)

        # 3. Store in cache & history
        self._cache[cache_key] = analysis_result
        self._history.insert(0, analysis_result)
        if len(self._history) > 30:
            self._history.pop()

        return analysis_result

    async def _generate_gemini_analysis(
        self,
        workload: WorkloadInput,
        estimate: CostEstimateResponse
    ) -> CostAnalysisResult:
        analysis_id = f"ANALYSIS-{uuid.uuid4().hex[:8].upper()}"
        timestamp = datetime.now(timezone.utc).isoformat()

        if not ai_query_service.is_configured():
            return self._build_deterministic_analysis(analysis_id, timestamp, workload, estimate)

        try:
            keys = ai_query_service.get_api_keys()
            prompt = self._build_gemini_prompt(workload, estimate)
            
            raw_json_text = ""
            for key in keys:
                try:
                    from google import genai
                    from google.genai import types

                    client = genai.Client(api_key=key)
                    response = client.models.generate_content(
                        model=settings.GEMINI_MODEL or "gemini-2.5-flash",
                        contents=prompt,
                        config=types.GenerateContentConfig(
                            system_instruction=GEMINI_COST_SYSTEM_PROMPT,
                            response_mime_type="application/json",
                            temperature=0.2
                        )
                    )
                    raw_json_text = response.text or ""
                    if raw_json_text:
                        break
                except Exception as e:
                    logger.warning(f"Gemini cost analysis with key failed: {e}")

            if not raw_json_text:
                return self._build_deterministic_analysis(analysis_id, timestamp, workload, estimate)

            return self._parse_gemini_response(raw_json_text, analysis_id, timestamp, workload, estimate)

        except Exception as e:
            logger.error(f"Error invoking Gemini for cost optimization: {e}", exc_info=True)
            return self._build_deterministic_analysis(analysis_id, timestamp, workload, estimate)

    def _build_gemini_prompt(self, workload: WorkloadInput, estimate: CostEstimateResponse) -> str:
        prompt_data = {
            "workload_parameters": workload.model_dump(),
            "selected_deployment": estimate.selected_deployment.model_dump(),
            "comparison_options": [opt.model_dump() for opt in estimate.comparison_options],
            "potential_monthly_savings_calculated": estimate.potential_monthly_savings,
            "cost_health": estimate.cost_health.model_dump() if estimate.cost_health else None,
            "pricing_metadata": estimate.pricing_metadata
        }
        return f"Workload Data & Deterministic Calculator Output for Analysis:\n{json.dumps(prompt_data, indent=2)}"

    def _parse_gemini_response(
        self,
        raw_text: str,
        analysis_id: str,
        timestamp: str,
        workload: WorkloadInput,
        estimate: CostEstimateResponse
    ) -> CostAnalysisResult:
        try:
            cleaned = raw_text.strip()
            if cleaned.startswith("```json"):
                cleaned = cleaned[7:]
            if cleaned.startswith("```"):
                cleaned = cleaned[3:]
            if cleaned.endswith("```"):
                cleaned = cleaned[:-3]
            cleaned = cleaned.strip()

            parsed = json.loads(cleaned)

            raw_recs = parsed.get("recommendations", [])
            recommendations: List[Recommendation] = []

            for idx, r in enumerate(raw_recs):
                rec_id = r.get("id") or f"rec-{idx + 1}"
                savings = r.get("estimated_monthly_savings")
                if savings is not None:
                    try:
                        savings = float(savings)
                    except (ValueError, TypeError):
                        savings = None

                why_context = {
                    "runtime_hours": f"{workload.monthly_uptime_hours} hrs/mo",
                    "compute_cost": f"${estimate.selected_deployment.breakdown.compute_cost:.2f}",
                    "daily_requests": f"{workload.requests_per_day:,} reqs/day",
                    "storage_gb": f"{workload.data_storage_gb} GB",
                    "backup_days": f"{workload.backup_retention_days} days"
                }

                recommendations.append(
                    Recommendation(
                        id=rec_id,
                        title=r.get("title", f"Optimization Recommendation #{idx + 1}"),
                        category=r.get("category", "compute"),
                        impact=r.get("impact", "medium"),
                        explanation=r.get("explanation", ""),
                        proposed_action=r.get("proposed_action", r.get("action", "")),
                        reason=r.get("reason", f"Workload factor: {r.get('category', 'compute')} utilization"),
                        estimated_impact=r.get("estimated_impact", f"{r.get('impact', 'Medium').capitalize()} impact on monthly expenditure"),
                        tradeoff=r.get("tradeoff", r.get("trade_offs", ["No critical architectural trade-off"])[0] if r.get("trade_offs") else None),
                        action=r.get("action", r.get("proposed_action", "")),
                        estimated_monthly_savings=savings,
                        trade_offs=r.get("trade_offs", []),
                        implementation_steps=r.get("implementation_steps", []),
                        why_context=why_context,
                        status="pending"
                    )
                )

            summary = parsed.get("summary") or parsed.get("gemini_summary") or "Architectural cost analysis completed."

            return CostAnalysisResult(
                analysis_id=analysis_id,
                timestamp=timestamp,
                workload=workload,
                selected_estimate=estimate.selected_deployment,
                comparison_options=estimate.comparison_options,
                potential_monthly_savings=estimate.potential_monthly_savings,
                cost_health=estimate.cost_health,
                cost_drivers=parsed.get("cost_drivers", [
                    f"Continuous compute hours ({estimate.selected_deployment.monthly_uptime_hours}h/mo)",
                    f"Active BSON document storage ({workload.data_storage_gb} GB)"
                ]),
                identified_waste=parsed.get("identified_waste", parsed.get("optimization_opportunities", [
                    "Cluster compute hours running during non-working intervals"
                ])),
                optimization_opportunities=parsed.get("optimization_opportunities", []),
                deployment_observations=parsed.get("deployment_observations", [
                    f"Selected {estimate.selected_deployment.name} meets {workload.environment_tier} operational requirements.",
                    f"High availability status: {'Enabled (Multi-AZ)' if estimate.selected_deployment.high_availability else 'Single-AZ (Cost-optimized)'}."
                ]),
                tradeoffs=parsed.get("tradeoffs", [
                    "Scheduled instances introduce a ~5-8 minute cold start delay when resuming.",
                    "Single-AZ deployments reduce infrastructure cost by ~50% vs Multi-AZ HA."
                ]),
                risks=parsed.get("risks", [
                    "Unindexed queries against nested finding arrays can rapidly exhaust monthly I/O allowance.",
                    "Accidental 24/7 continuous operation increases monthly compute expenditure."
                ]),
                recommended_next_steps=parsed.get("recommended_next_steps", [
                    "Implement automated CloudWatch EventBridge schedules for staging.",
                    "Create multikey compound indexes on frequently filtered nested fields."
                ]),
                gemini_summary=summary,
                recommendations=recommendations,
                missing_information=parsed.get("missing_information", [
                    "Peak concurrency during field shift handovers",
                    "Expected binary attachment payload sizes"
                ]),
                is_cached=False,
                is_demo_mode=True,
                gemini_model=settings.GEMINI_MODEL
            )

        except Exception as e:
            logger.warning(f"Failed to parse Gemini cost response: {e}. Using deterministic fallback.")
            return self._build_deterministic_analysis(analysis_id, timestamp, workload, estimate)

    def _build_deterministic_analysis(
        self,
        analysis_id: str,
        timestamp: str,
        workload: WorkloadInput,
        estimate: CostEstimateResponse
    ) -> CostAnalysisResult:
        selected_opt = estimate.selected_deployment
        is_continuous = selected_opt.monthly_uptime_hours >= 700
        hourly_compute = selected_opt.breakdown.compute_cost
        
        # Calculate concrete savings for scheduling
        scheduled_savings = round(hourly_compute * (1.0 - (160.0 / 730.0)), 2) if is_continuous else 0.0

        why_compute = {
            "runtime_hours": f"{selected_opt.monthly_uptime_hours} hrs/month",
            "compute_contribution": f"${selected_opt.breakdown.compute_cost:.2f}/mo",
            "workload_requests": f"{workload.requests_per_day:,} requests/day",
            "instance_type": selected_opt.instance_type
        }

        why_indexing = {
            "daily_requests": f"{workload.requests_per_day:,} req/day",
            "monthly_ios": f"{int(workload.requests_per_day * 30 * 1.25):,} I/Os",
            "read_write_ratio": f"{workload.read_percentage}% Read / {workload.write_percentage}% Write",
            "io_cost": f"${selected_opt.breakdown.io_cost:.2f}/mo"
        }

        why_storage = {
            "data_storage": f"{workload.data_storage_gb} GB",
            "backup_days": f"{workload.backup_retention_days} days",
            "storage_cost": f"${selected_opt.breakdown.storage_cost:.2f}/mo",
            "backup_cost": f"${selected_opt.breakdown.backup_cost:.2f}/mo"
        }

        why_budget = {
            "estimated_cost": f"${selected_opt.monthly_cost:.2f}/mo",
            "environment": workload.environment_tier.capitalize(),
            "region": workload.region
        }

        recommendations = [
            Recommendation(
                id="rec-sched-01",
                title="Implement Automated Start/Stop Schedule for Non-Production Workloads",
                category="scheduling",
                impact="high",
                explanation=f"Running a DocumentDB cluster 24/7 ({selected_opt.monthly_uptime_hours} hrs) incurs charges during inactive nights and weekends. For development and coursework, scheduling active hours to 8h/day (160h/month) eliminates ~78% of compute expenses.",
                reason="Continuous runtime is the largest contributor to the current estimate.",
                estimated_impact="High cost reduction (~78% compute savings, up to $44.46/mo)",
                tradeoff="Cluster requires ~5-8 minutes startup delay upon scheduled resumption.",
                action="Configure AWS EventBridge cron rules with AWS Lambda to automatically stop instances at 6 PM and resume at 8 AM weekdays.",
                proposed_action="Configure AWS EventBridge rules to trigger AWS Lambda start/stop functions on the DocumentDB cluster.",
                estimated_monthly_savings=scheduled_savings if is_continuous else None,
                trade_offs=[
                    "Cluster takes ~5-8 minutes to start up upon scheduled trigger",
                    "Requires CloudWatch EventBridge and Lambda setup"
                ],
                implementation_steps=[
                    "Create an AWS IAM Role with docdb:StartDBCluster and docdb:StopDBCluster permissions.",
                    "Deploy two lightweight Python AWS Lambda functions for start and stop events.",
                    "Configure EventBridge cron schedules (e.g., cron(0 8 ? * MON-FRI *) for start, cron(0 18 ? * MON-FRI *) for stop)."
                ],
                why_context=why_compute,
                status="pending"
            ),
            Recommendation(
                id="rec-index-02",
                title="Create Multikey Compound Indexes on High-Frequency Nested Fields",
                category="architecture",
                impact="medium",
                explanation="Inspecting nested findings and sub-issues without appropriate indexes causes full collection table scans, dramatically multiplying I/O charges and latency.",
                reason=f"High request volume ({workload.requests_per_day:,} req/day) across nested inspection subdocuments requires indexed lookups.",
                estimated_impact="Reduces read I/O operations by up to 85% and eliminates query latency spikes.",
                tradeoff="Indexes consume a small amount of additional cluster storage (~5-10%).",
                action="Add compound multikey indexes on 'findings.severity', 'findings.category', and 'status'.",
                proposed_action="Add multikey indexes on 'findings.severity', 'findings.category', and 'status' fields.",
                estimated_monthly_savings=None,
                trade_offs=[
                    "Indexes consume a small amount of additional cluster storage (~5-10%)",
                    "Slight write latency overhead during heavy bulk report insertions"
                ],
                implementation_steps=[
                    "Run db.inspection_reports.createIndex({'findings.severity': 1, 'category': 1}) via DocumentDB mongo shell.",
                    "Run db.inspection_reports.createIndex({'status': 1, 'inspection_date': -1}).",
                    "Monitor index usage via explain('executionStats') query analyzer."
                ],
                why_context=why_indexing,
                status="pending"
            ),
            Recommendation(
                id="rec-budget-03",
                title="Configure AWS Budgets with Multi-Threshold Alarm Notifications",
                category="monitoring",
                impact="high",
                explanation="Protects against accidental runaway costs, forgotten test clusters, or unindexed traffic spikes.",
                reason="Unmonitored cloud resources risk unintentional billing spikes during active academic development.",
                estimated_impact="Eliminates risk of surprise cloud billing by alerting at defined spend thresholds.",
                tradeoff="Alarms are advisory and do not automatically kill instances unless linked with SSM automation.",
                action="Set a strict AWS Budget threshold at $10.00/month with 50%, 80%, and 100% email alerts.",
                proposed_action="Set a strict AWS Budget threshold at $10.00/month with 50%, 80%, and 100% email alerts.",
                estimated_monthly_savings=None,
                trade_offs=[
                    "Alarms are advisory and do not automatically kill running instances unless configured with SSM automation"
                ],
                implementation_steps=[
                    "Navigate to AWS Billing & Cost Management > Budgets.",
                    "Create a Cost Budget with Monthly recurring cadence of $10.00.",
                    "Add notification triggers at 50% ($5), 80% ($8), and 100% ($10) sent to project team emails."
                ],
                why_context=why_budget,
                status="pending"
            ),
            Recommendation(
                id="rec-storage-04",
                title="Optimize Backup Retention Window for Non-Critical Environments",
                category="storage",
                impact="low",
                explanation=f"Current backup retention is configured to {workload.backup_retention_days} days. For testing environments, 1 to 3 days retention is sufficient, keeping backup costs well within the free tier allocation.",
                reason=f"Extended retention window ({workload.backup_retention_days} days) in a non-production {workload.environment_tier} environment.",
                estimated_impact=f"Saves ${selected_opt.breakdown.backup_cost:.2f}/mo by eliminating storage beyond free 100% cluster size.",
                tradeoff="Reduced historical point-in-time recovery window (1-3 days instead of multiple weeks).",
                action="Adjust backup retention period to 1 day for development clusters.",
                proposed_action="Adjust backup retention period to 1 day for development clusters.",
                estimated_monthly_savings=selected_opt.breakdown.backup_cost or None,
                trade_offs=[
                    "Reduced historical point-in-time recovery window (1 day instead of multiple weeks)"
                ],
                implementation_steps=[
                    "Modify DocumentDB cluster configuration: BackupRetentionPeriod = 1.",
                    "Take a manual snapshot prior to major testing cycles if long-term preservation is needed."
                ],
                why_context=why_storage,
                status="pending"
            )
        ]

        cost_drivers = [
            f"Compute hours ({selected_opt.monthly_uptime_hours} hrs/mo) accounting for {round((selected_opt.breakdown.compute_cost / max(0.01, selected_opt.monthly_cost)) * 100)}% of total cost",
            f"Active BSON storage ({workload.data_storage_gb} GB @ $0.10/GB-mo)",
            f"Monthly request volume ({workload.requests_per_day:,} req/day) generating ~{int(workload.requests_per_day * 30 * 1.25):,} monthly I/O operations"
        ]

        identified_waste = []
        if is_continuous:
            identified_waste.append("Cluster running 24/7 during nights and weekends without active user requests")
        if workload.backup_retention_days > 7 and not selected_opt.high_availability:
            identified_waste.append(f"Extended backup retention ({workload.backup_retention_days} days) for non-production environment")

        deployment_observations = [
            f"Selected configuration ({selected_opt.name}) provides {selected_opt.suitability}",
            f"Availability: {'High Availability with automated failover' if selected_opt.high_availability else 'Single-AZ non-HA (suitable for non-production workloads)'}.",
            f"Operational Complexity: {selected_opt.operational_complexity}."
        ]

        tradeoffs = [
            "Scheduled instances reduce monthly compute cost from $56.94 to $12.48, but introduce a 5-8 minute spin-up delay.",
            "Single-AZ deployments reduce infrastructure cost by ~50% vs Multi-AZ, at the expense of automatic failover."
        ]

        risks = [
            "Burst credits on db.t3.medium instances may deplete under sustained continuous heavy CPU loads.",
            "Unindexed queries across nested inspection arrays can rapidly multiply monthly I/O billing."
        ]

        next_steps = [
            "Apply the automated start/stop schedule for staging environments.",
            "Create multikey compound indexes on findings.severity and findings.category."
        ]

        summary = (
            f"For your workload of {workload.requests_per_day:,} daily requests and {workload.data_storage_gb} GB storage in {workload.region}, "
            f"the estimated monthly cost for {selected_opt.name} is ${selected_opt.monthly_cost:.2f}. "
            f"Implementing automated start/stop scheduling can reduce monthly compute costs significantly while maintaining full DocumentDB functionality during working hours."
        )

        return CostAnalysisResult(
            analysis_id=analysis_id,
            timestamp=timestamp,
            workload=workload,
            selected_estimate=selected_opt,
            comparison_options=estimate.comparison_options,
            potential_monthly_savings=estimate.potential_monthly_savings,
            cost_health=estimate.cost_health,
            cost_drivers=cost_drivers,
            identified_waste=identified_waste,
            optimization_opportunities=identified_waste,
            deployment_observations=deployment_observations,
            tradeoffs=tradeoffs,
            risks=risks,
            recommended_next_steps=next_steps,
            gemini_summary=summary,
            recommendations=recommendations,
            missing_information=[
                "Actual traffic distribution across business vs non-business hours",
                "Expected document upload sizes (KB/MB per report with image attachments)"
            ],
            is_cached=False,
            is_demo_mode=True,
            gemini_model=settings.GEMINI_MODEL
        )

    def get_history(self) -> List[CostAnalysisResult]:
        return self._history

    def update_recommendation_status(self, rec_id: str, new_status: str) -> bool:
        updated = False
        for analysis in self._history:
            for rec in analysis.recommendations:
                if rec.id == rec_id:
                    rec.status = new_status
                    updated = True
        return updated

    def clear_history(self) -> None:
        self._history.clear()
        self._cache.clear()

cost_optimizer_service = CostOptimizerService()
